export const content = {
  en: {
    blog: "BLOG",
    contact: "CONTACT",
    toggleBtn: "AR",
    heroText: "RTL and Arabic SEO, simplified.",
    heropar: "Instant scans for RTL, AR-SEO, fonts, and accessibility. Fix hints + live preview.",
    herobtn1: "Try Now",
    herobtn2: "View Source",
    downloadFixed: "Download Fixed Code",
    analyzeBtn: "Analyze Code",
    score: "Score:",
    copyrights: "© 2025 Arabify. All rights reserved.",
    upFile: "Upload File",
    fileUped: "File Uploaded (Change?)",
    errtypeStructure: "structure",
    errtypeAlt: "a11y",
    errtypeMeta: "meta",
    errtypeLanguage: "language",
    msgMissingHeader: "We couldn't find a <header> tag. Consider replacing <div className='header'> with <header>.",
    msgMissingNav: "We couldn't find a <nav> tag. Consider replacing <div className='nav'> with <nav>.",
    msgMissingFooter: "We couldn't find a <footer> tag. Consider adding one for better structure.",
    msgMissingAlt: "Image #{id} is missing an 'alt' attribute.",
    msgMissingMetaCharset: "Missing <meta charset='utf-8'> tag for proper character encoding.",
    msgMissingMetaViewport: "Missing <meta name='viewport' content='width=device-width, initial-scale=1'> tag for responsive design.",
    msgMissingMetaDescription: "Missing <meta name='description' content='...'> tag for SEO optimization.",
    msgMissingMetaKeywords: "Missing <meta name='keywords' content='...'> tag for SEO optimization.",
    msgMissingMetaAuthor: "Missing <meta name='author' content='...'> tag for SEO optimization.",
    msgMissingLangAttribute: "The <html> tag is missing a 'lang' attribute.",
    msgMissingDirAttribute: "The <html> tag is missing a 'dir' attribute.",
    fixScroll: "Added 'scroll-behavior: smooth' to html for better user experience.",
    fixMarginLeft: "Replaced 'margin-left' with 'margin-inline-start' to automatically flip spacing in RTL mode.",
    fixMarginRight: "Replaced 'margin-right' with 'margin-inline-end' to automatically flip spacing in RTL mode.",
    fixPaddingLeft: "Replaced 'padding-left' with 'padding-inline-start' to support RTL.",
    fixPaddingRight: "Replaced 'padding-right' with 'padding-inline-end' to support RTL.",
    fixTextAlign: "Replaced 'text-align: left/right' with 'start/end' so text aligns correctly in Arabic.",
    warnPx: "Found fixed 'px' values larger than 5px. Use 'rem' for fonts and spacing to ensure accessibility."
  },
  ar: {
    blog: "مدونة",
    contact: "تواصل معنا",
    toggleBtn: "EN",
    heroText: "ظبط محركات البحث و التعريب بشكل مبسط.",
    heropar: "فحوصات فورية لمحركات البحث، الخطوط، وسهولة الوصول. نصائح للإصلاح + معاينة مباشرة.",
    herobtn1: "جرب فحص سريع",
    herobtn2: "عرض المصدر",
    downloadFixed: "تحميل الكود المصحح",
    analyzeBtn: "تحليل الكود",
    score: "النقاط:",
    copyrights: "© 2025 عَرِّب. جميع الحقوق محفوظة.",
    upFile: "رفع ملف",
    fileUped: "تم رفع الملف (تغيير؟)",
    errtypeStructure: "الهيكلية",
    errtypeAlt: "سهولة الوصول",
    errtypeMeta: "الميتا",
    errtypeLanguage: "اللغة",
    msgMissingHeader: "لم نتمكن من العثور على وسم <header>. فكر في استبدال <div className='header'> بـ <header>.",
    msgMissingNav: "لم نتمكن من العثور على وسم <nav>. فكر في استبدال <div className='nav'> بـ <nav>.",
    msgMissingFooter: "لم نتمكن من العثور على وسم <footer>. فكر في إضافة واحد لتحسين الهيكلية.",
    msgMissingAlt: "الصورة #{id} تفتقد وسم 'alt'.",
    msgMissingMetaCharset: "يفتقد وسم <meta charset='utf-8'> لترميز الأحرف بشكل صحيح.",
    msgMissingMetaViewport: "يفتقد وسم <meta name='viewport' content='width=device-width, initial-scale=1'> لتصميم متجاوب.",
    msgMissingMetaDescription: "يفتقد وسم <meta name='description' content='...'> لضبط محركات البحث.",
    msgMissingMetaKeywords: "يفتقد وسم <meta name='keywords' content='...'> لضبط محركات البحث.",
    msgMissingMetaAuthor: "يفتقد وسم <meta name='author' content='...'> لضبط محركات البحث.",
    msgMissingLangAttribute: "وسم <html> يفتقد وسم 'lang'.",
    msgMissingDirAttribute: "وسم <html> يفتقد وسم 'dir'.",
    fixScroll: "تم إضافة 'scroll-behavior: smooth' لتحسين تجربة التمرير.",
    fixMarginLeft: "تم استبدال 'margin-left' بـ 'margin-inline-start' لقلب المسافات تلقائياً في العربية.",
    fixMarginRight: "تم استبدال 'margin-right' بـ 'margin-inline-end' لقلب المسافات تلقائياً في العربية.",
    fixPaddingLeft: "تم استبدال 'padding-left' بـ 'padding-inline-start' لدعم الاتجاهين.",
    fixPaddingRight: "تم استبدال 'padding-right' بـ 'padding-inline-end' لدعم الاتجاهين.",
    fixTextAlign: "تم استبدال 'text-align' بـ 'start/end' لضمان محاذاة النص بشكل صحيح.",
    warnPx: "تم العثور على قيم 'px' أكبر من 5px. استخدم 'rem' للخطوط والمسافات لضمان سهولة الوصول."
  }
};